- hosts: all
  tasks:
  - name: Ansible create file if it doesn't exist example
    file:
     path: "/tmp/{{filename}}"
     state: touch
   tasks:
  - name: Ansible create file if it doesn't exist example
    file:
     path: "/tmp/myfolder/{{filename}}"
     state: touch  
   
